const data = [
  {
    NO: 1,
    "NAMA PEDAGANG": "JURAID",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 2,
    "NAMA PEDAGANG": "IRUS",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 3,
    "NAMA PEDAGANG": "JONI",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "AIR MINUM",
  },
  {
    NO: 4,
    "NAMA PEDAGANG": "YAYUK",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "SEMBAKO",
  },
  {
    NO: 5,
    "NAMA PEDAGANG": "MAMAK TITO",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "SEMBAKO",
  },
  {
    NO: 6,
    "NAMA PEDAGANG": "LANDRY",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "LAUNDRY ",
  },
  {
    NO: 7,
    "NAMA PEDAGANG": "SALEH",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 8,
    "NAMA PEDAGANG": "RIDEH",
    "ALAMAT TEMPAT TINGGAL": "RT 001",
    "JENIS USAHA": "WARUNG MAKAN",
  },
  {
    NO: 9,
    "NAMA PEDAGANG": "Maya Sari",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 10,
    "NAMA PEDAGANG": "Siti Aisah",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "JASA KEUANGAN",
  },
  {
    NO: 11,
    "NAMA PEDAGANG": "Arsuni",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Bengkel",
  },
  {
    NO: 12,
    "NAMA PEDAGANG": "Darsuni",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 13,
    "NAMA PEDAGANG": "Miar",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Warung Nasi Goreng/Nasi Campur",
  },
  {
    NO: 14,
    "NAMA PEDAGANG": "Dedy",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Bengkel Motor",
  },
  {
    NO: 15,
    "NAMA PEDAGANG": "Syahril",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Jual Ayam Potong",
  },
  {
    NO: 16,
    "NAMA PEDAGANG": "Mardiana",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Jual ES dan Gorengan dll",
  },
  {
    NO: 17,
    "NAMA PEDAGANG": "Maysarah",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Kedai ES",
  },
  {
    NO: 18,
    "NAMA PEDAGANG": "Ani Susanti",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Warung Nasi Kuning",
  },
  {
    NO: 19,
    "NAMA PEDAGANG": "Sopianur",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Penjahit",
  },
  {
    NO: 20,
    "NAMA PEDAGANG": "H. Ediansyah",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Toko Bangunan",
  },
  {
    NO: 21,
    "NAMA PEDAGANG": "Hamdi",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Depot AIR Minum",
  },
  {
    NO: 22,
    "NAMA PEDAGANG": "Adil",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Feri Penyebrangan",
  },
  {
    NO: 23,
    "NAMA PEDAGANG": "Masitah",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "Warung Nasi Kuning",
  },
  {
    NO: 24,
    "NAMA PEDAGANG": "GUGUN",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "SEMBAKO",
  },
  {
    NO: 25,
    "NAMA PEDAGANG": "KEDAI TANJUNG KRIU",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "KEDAI",
  },
  {
    NO: 26,
    "NAMA PEDAGANG": "MIAR ",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "ES",
  },
  {
    NO: 27,
    "NAMA PEDAGANG": "DARNOK/ TIKA",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "SAYURAN",
  },
  {
    NO: 28,
    "NAMA PEDAGANG": "TIK",
    "ALAMAT TEMPAT TINGGAL": "RT 002",
    "JENIS USAHA": "SEMBAKO",
  },
  {
    NO: 29,
    "NAMA PEDAGANG": "Hj. Arpiah",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Toko Bangunan",
  },
  {
    NO: 30,
    "NAMA PEDAGANG": "Hj. Halipah",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Toko Bangunan",
  },
  {
    NO: 31,
    "NAMA PEDAGANG": "Wati",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 32,
    "NAMA PEDAGANG": "Siti Rohayah",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Jual Es",
  },
  {
    NO: 33,
    "NAMA PEDAGANG": "Yaslinta",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Toko Sayur",
  },
  {
    NO: 34,
    "NAMA PEDAGANG": "Vera Wahyuni",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "ATK",
  },
  {
    NO: 35,
    "NAMA PEDAGANG": "H.Ali Murdana",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Toko Bangunan",
  },
  {
    NO: 36,
    "NAMA PEDAGANG": "Madiana",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 37,
    "NAMA PEDAGANG": "Jumran",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 38,
    "NAMA PEDAGANG": "Upa Gasiah",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Warung Bakso",
  },
  {
    NO: 39,
    "NAMA PEDAGANG": "Arbayah",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 40,
    "NAMA PEDAGANG": "Ervina",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Pakaian",
  },
  {
    NO: 41,
    "NAMA PEDAGANG": "Rosi Andarwati",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Klinik Bidan",
  },
  {
    NO: 42,
    "NAMA PEDAGANG": "Siti Sakdiah",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Pakaian",
  },
  {
    NO: 43,
    "NAMA PEDAGANG": "Hj. Rusmini",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "Toko Lemari dan Parabotan Rtangga",
  },
  {
    NO: 44,
    "NAMA PEDAGANG": "KEDAI GEREU/MECCA",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "ES",
  },
  {
    NO: 45,
    "NAMA PEDAGANG": "NANIK",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "NASI KUNING",
  },
  {
    NO: 46,
    "NAMA PEDAGANG": "Madi",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "PENJUAL IKAN",
  },
  {
    NO: 47,
    "NAMA PEDAGANG": "JURAI",
    "ALAMAT TEMPAT TINGGAL": "RT 003",
    "JENIS USAHA": "ES",
  },
  {
    NO: 48,
    "NAMA PEDAGANG": "Dewi Sartika",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "KIOS Pulsa",
  },
  {
    NO: 49,
    "NAMA PEDAGANG": "Robi Darwins",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 50,
    "NAMA PEDAGANG": "Hariyanto",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Depot AIR Minum",
  },
  {
    NO: 51,
    "NAMA PEDAGANG": "Fitriyani",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Kios ES & Sembako",
  },
  {
    NO: 52,
    "NAMA PEDAGANG": "Arsuni",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Depot AIR Minum",
  },
  {
    NO: 53,
    "NAMA PEDAGANG": "Ungkin Efendi",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Pedagang Keliling (Pentol)",
  },
  {
    NO: 54,
    "NAMA PEDAGANG": "Efendi",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Bengkel",
  },
  {
    NO: 55,
    "NAMA PEDAGANG": "Ari",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Kedai ES",
  },
  {
    NO: 56,
    "NAMA PEDAGANG": "Susanti",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 57,
    "NAMA PEDAGANG": "Ratna",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 58,
    "NAMA PEDAGANG": "Habibah",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 59,
    "NAMA PEDAGANG": "Zuniar",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Warung Makan",
  },
  {
    NO: 60,
    "NAMA PEDAGANG": "Eniwati",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Pedagang Keliling Kue, Gorengan dan ES",
  },
  {
    NO: 61,
    "NAMA PEDAGANG": "Siti Setiawan",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Jual Kue Basah dan Gorengan",
  },
  {
    NO: 62,
    "NAMA PEDAGANG": "Nia Wati",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Warung Makan",
  },
  {
    NO: 63,
    "NAMA PEDAGANG": "Saldina",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Warung Gado-gado",
  },
  {
    NO: 64,
    "NAMA PEDAGANG": "Rusnawati",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Kedai ES dan Gorengan",
  },
  {
    NO: 65,
    "NAMA PEDAGANG": "Ujik",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 66,
    "NAMA PEDAGANG": "Erna",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 67,
    "NAMA PEDAGANG": "AINI",
    "ALAMAT TEMPAT TINGGAL": "RT 004",
    "JENIS USAHA": "SEMBAKO",
  },
  {
    NO: 68,
    "NAMA PEDAGANG": "Nur Afuansyah",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 69,
    "NAMA PEDAGANG": "Hj. Mardiani",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Toko Pakaian dan Perbot R.Tangga",
  },
  {
    NO: 70,
    "NAMA PEDAGANG": "Puspa Miati",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "WARUNG Makan Gado-Gado",
  },
  {
    NO: 71,
    "NAMA PEDAGANG": "Dahlia",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 72,
    "NAMA PEDAGANG": "Ratna Hakim/KERIS",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 73,
    "NAMA PEDAGANG": "Subli",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Penjahit",
  },
  {
    NO: 74,
    "NAMA PEDAGANG": "Udin",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Bengkel Motor",
  },
  {
    NO: 75,
    "NAMA PEDAGANG": "Aida",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Warung Bakso",
  },
  {
    NO: 76,
    "NAMA PEDAGANG": "Sarmidi",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Kosmetik/Pakaian",
  },
  {
    NO: 77,
    "NAMA PEDAGANG": "Isniong",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Pedagang Keliling Jual ES dan Gorengan",
  },
  {
    NO: 78,
    "NAMA PEDAGANG": "RAHMA WATI",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "BAKSO",
  },
  {
    NO: 79,
    "NAMA PEDAGANG": "MALAH ",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "SEMBAKO",
  },
  {
    NO: 80,
    "NAMA PEDAGANG": "GUMRI",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Depot AIR Minum",
  },
  {
    NO: 81,
    "NAMA PEDAGANG": "ELSA NABILA",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "ES DAN GORENGAN",
  },
  {
    NO: 82,
    "NAMA PEDAGANG": "EMIYATI",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "ATK",
  },
  {
    NO: 83,
    "NAMA PEDAGANG": "Tina",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Warung Makan",
  },
  {
    NO: 84,
    "NAMA PEDAGANG": "Syharuddin",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 85,
    "NAMA PEDAGANG": "Titin Yani",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 86,
    "NAMA PEDAGANG": "Tatang",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Bengkel Motor",
  },
  {
    NO: 87,
    "NAMA PEDAGANG": "Gatot Subroto",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Kios Sayur",
  },
  {
    NO: 88,
    "NAMA PEDAGANG": "Rusandi",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Kios Ikan",
  },
  {
    NO: 89,
    "NAMA PEDAGANG": "Mardani Nuddin",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Salon",
  },
  {
    NO: 90,
    "NAMA PEDAGANG": "Yusuf",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Toko Mainan",
  },
  {
    NO: 91,
    "NAMA PEDAGANG": "Mujianto",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 92,
    "NAMA PEDAGANG": "Muklis",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 93,
    "NAMA PEDAGANG": "Yuyun",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Salon",
  },
  {
    NO: 94,
    "NAMA PEDAGANG": "Timah",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Pedagang Keliling Jual ES dan Gorengan",
  },
  {
    NO: 95,
    "NAMA PEDAGANG": "Saidah",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Pedagang Keliling Jual ES dan Gorengan",
  },
  {
    NO: 96,
    "NAMA PEDAGANG": "Jumiyati",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Pedagang Keliling Jual ES dan Gorengan",
  },
  {
    NO: 97,
    "NAMA PEDAGANG": "Isna",
    "ALAMAT TEMPAT TINGGAL": "RT 006 ",
    "JENIS USAHA": "Pedagang Keliling Jual ES dan Gorengan",
  },
  {
    NO: 98,
    "NAMA PEDAGANG": "M. Solihudin",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Konter Pulsa",
  },
  {
    NO: 99,
    "NAMA PEDAGANG": "Owarto",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Depot AIR Minum",
  },
  {
    NO: 100,
    "NAMA PEDAGANG": "Sarniwati",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Warung ES",
  },
  {
    NO: 101,
    "NAMA PEDAGANG": "Pitri Sari",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Warung ES",
  },
  {
    NO: 102,
    "NAMA PEDAGANG": "Rusniah",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Warung ES dan Sayur",
  },
  {
    NO: 103,
    "NAMA PEDAGANG": "Sopian",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 104,
    "NAMA PEDAGANG": "Siti Maya",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Warung Makan/Warung ES",
  },
  {
    NO: 105,
    "NAMA PEDAGANG": "Hj. Suma",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Jual Beli EMAS",
  },
  {
    NO: 106,
    "NAMA PEDAGANG": "Abdul Fatah",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Bengkel Motor",
  },
  {
    NO: 107,
    "NAMA PEDAGANG": "UNMING",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "SEMBAKO",
  },
  {
    NO: 108,
    "NAMA PEDAGANG": "EVI",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "PENTOL",
  },
  {
    NO: 109,
    "NAMA PEDAGANG": "AHMAD/UPUNG",
    "ALAMAT TEMPAT TINGGAL": "RT 007",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 110,
    "NAMA PEDAGANG": "Mirhan",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Feri Penyebrangan",
  },
  {
    NO: 111,
    "NAMA PEDAGANG": "Jumaidi",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 112,
    "NAMA PEDAGANG": "Hamiah",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Kios Sayur",
  },
  {
    NO: 113,
    "NAMA PEDAGANG": "Saidin",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 114,
    "NAMA PEDAGANG": "Maymunah",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Warung ES",
  },
  {
    NO: 115,
    "NAMA PEDAGANG": "Abdul Hadi",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Toko Sayur/Sembako",
  },
  {
    NO: 116,
    "NAMA PEDAGANG": "Desi",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Kedai ES",
  },
  {
    NO: 117,
    "NAMA PEDAGANG": "Yuniansyah",
    "ALAMAT TEMPAT TINGGAL": "RT 009",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 118,
    "NAMA PEDAGANG": "Salsiah",
    "ALAMAT TEMPAT TINGGAL": "RT 009",
    "JENIS USAHA": "Warung ES",
  },
  {
    NO: 119,
    "NAMA PEDAGANG": "Hj. Nukni",
    "ALAMAT TEMPAT TINGGAL": "RT 009",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 120,
    "NAMA PEDAGANG": "Freti Sentia",
    "ALAMAT TEMPAT TINGGAL": "RT 009",
    "JENIS USAHA": "Kedai ES BOBA",
  },
  {
    NO: 121,
    "NAMA PEDAGANG": "ERWIN",
    "ALAMAT TEMPAT TINGGAL": "RT 009",
    "JENIS USAHA": "SAYUR",
  },
  {
    NO: 122,
    "NAMA PEDAGANG": "MARLINA",
    "ALAMAT TEMPAT TINGGAL": "RT 009",
    "JENIS USAHA": "GORENGAN",
  },
  {
    NO: 123,
    "NAMA PEDAGANG": "Tania",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Warung ES dan Gorengan",
  },
  {
    NO: 124,
    "NAMA PEDAGANG": "Isnawati",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Warung ES dan Cemilan",
  },
  {
    NO: 125,
    "NAMA PEDAGANG": "Ristawati",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Warung Soto",
  },
  {
    NO: 126,
    "NAMA PEDAGANG": "Resa",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Accesoris dan Pakaian",
  },
  {
    NO: 127,
    "NAMA PEDAGANG": "Sarinah",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 128,
    "NAMA PEDAGANG": "Marni",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Toko Pakaian",
  },
  {
    NO: 129,
    "NAMA PEDAGANG": "Asminiwati",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Warung ES",
  },
  {
    NO: 130,
    "NAMA PEDAGANG": "Eva",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Warung Es & Sembako",
  },
  {
    NO: 131,
    "NAMA PEDAGANG": "Elvi",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 132,
    "NAMA PEDAGANG": "Mirna",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Toko Pakaian",
  },
  {
    NO: 133,
    "NAMA PEDAGANG": "Rodi Efendi",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Warung ES",
  },
  {
    NO: 134,
    "NAMA PEDAGANG": "Amran",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Kios Ikan",
  },
  {
    NO: 135,
    "NAMA PEDAGANG": "Iwan Irawan",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 136,
    "NAMA PEDAGANG": "H.Imran",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Toko Pakaian",
  },
  {
    NO: 137,
    "NAMA PEDAGANG": "Ratni",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Kedai Es/Toko Sayur",
  },
  {
    NO: 138,
    "NAMA PEDAGANG": "Yani",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Toko Sayur",
  },
  {
    NO: 139,
    "NAMA PEDAGANG": "Ani",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 140,
    "NAMA PEDAGANG": "Fitri",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "Toko Pakaian",
  },
  {
    NO: 141,
    "NAMA PEDAGANG": "Zahratul Baiti",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "KIOS PULSA dan Accesoris",
  },
  {
    NO: 142,
    "NAMA PEDAGANG": "Rusmah",
    "ALAMAT TEMPAT TINGGAL": "RT 005",
    "JENIS USAHA": "Kedai ES",
  },
  {
    NO: 143,
    "NAMA PEDAGANG": "Telma",
    "ALAMAT TEMPAT TINGGAL": "RT 006",
    "JENIS USAHA": "Jual Bensin",
  },
  {
    NO: 144,
    "NAMA PEDAGANG": "Ningsi",
    "ALAMAT TEMPAT TINGGAL": "RT 008",
    "JENIS USAHA": "Warung ES",
  },
  {
    NO: 145,
    "NAMA PEDAGANG": "DEVIANSYAH",
    "ALAMAT TEMPAT TINGGAL": "RT 010",
    "JENIS USAHA": "BENGKEL",
  },
  {
    NO: 146,
    "NAMA PEDAGANG": "Maraiani",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 147,
    "NAMA PEDAGANG": "Hj. Jamilah",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Toko Pakaian",
  },
  {
    NO: 148,
    "NAMA PEDAGANG": "Abdawati",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Pedagang Keliling Jual ES dan Gorengan",
  },
  {
    NO: 149,
    "NAMA PEDAGANG": "Sabran",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 150,
    "NAMA PEDAGANG": "Herdri",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Sembako",
  },
  {
    NO: 151,
    "NAMA PEDAGANG": "Salmi",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Gorengan",
  },
  {
    NO: 152,
    "NAMA PEDAGANG": "Ani",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Kedai ES / Sosis",
  },
  {
    NO: 153,
    "NAMA PEDAGANG": "Isniah",
    "ALAMAT TEMPAT TINGGAL": "",
    "JENIS USAHA": "Sembako",
  },
];

export default data;
